In [1]:
import numpy as np

In [2]:
matrixListem = [[10,20,30],[20,30,40],[40,50,60]]


In [3]:
np.array(matrixListem)

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

## arange

In [4]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange((10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace


In [11]:
arr = np.linspace(10, 100, num=7)

In [12]:
print(arr)

[ 10.  25.  40.  55.  70.  85. 100.]


## eye

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## random

In [16]:
np.random.randn(3,4)

array([[ 0.74917342, -0.23850485,  0.10860561,  1.35962758],
       [ 1.49138893, -1.12199035, -0.84071288,  1.29953101],
       [ 0.6669845 , -0.23272005, -2.27270436,  0.13816125]])

In [18]:
np.random.randn(4)

array([-1.71620252, -0.71561914,  0.25841148, -0.7154533 ])

In [20]:
np.random.randint(4)

1

In [21]:
np.random.randint(1,10)

1

In [22]:
np.random.randint(1,10,7)

array([1, 4, 4, 4, 8, 2, 8])

In [24]:
benimNumpyDizim = np.arange(30)

In [25]:
benimNumpyDizim


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## numpy dizi methodları

In [30]:
np.reshape(benimNumpyDizim, (5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
np.argmax(benimNumpyDizim)

29

In [32]:
benimNumpyDizim.max()

29

In [33]:
np.shape(benimNumpyDizim)

(30,)

In [28]:
np.reshape(benimNumpyDizim, (5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
np.reshape(benimNumpyDizim, (5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
np.reshape(benimNumpyDizim, (5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])